image: registry.gitlab.com/remipassmoilesel/personal-website/build-image:0.11

cache:
  paths:
    - .pnpm-store
    - node_modules/

continuous-integration:
  script:
    - ./scripts/continuous-integration.sh
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
