export const CLI_COMMANDS = [
  'git show HEAD~1',
  "git commit -m 'Refactoring in progress'",
  'git clean',
  'kubectl logs -f -l app.kubernetes.io/name=batch | tee batch.log',
  'sudo pacman -Qi borg',
  'notes search ProxyPass',
  'pass -c pro/believeit/production-04/admin',
  'git rebase -i 5ad68603',
  'git branch -D feature/better-dashboard',
  'ava-cli end-to-end-tests staging',
  'ava-cli deploy staging 5c9e9d5e',
  'git lg',
  'z projects',
  'sudo umount /dev/sdc1',
  'sudo dd if=manjaro-xfce-20.2-201203-linux59.iso of=/dev/sdc1 bs=4096 && sync',
  'git checkout -b doc/deployment',
  'git push --set-upstream origin doc/deployment',
  'mkdir infrastructure',
  'chmod +x k3s-install.sh',
  'k3s kubectl get all',
  'kubectl get all --all-namespaces',
  'terraform plan',
  'terraform apply',
  'curl -sfL https://get.k3s.io -o k3s-install.sh',
  'helm list',
  'kustomize build . | kubectl apply -f -',
  'helm upgrade -f production-values.yaml prometheus ./prometheus',
  'sudo systemctl status k3s',
  'sudo systemctl status sshd',
  'ss -ltnp',
  'rsync -avz mtp://Google_Pixel_3a_/ backup-pixel-2020-11-20',
  'pass generate -c pro/believeit/production-03/smtp-su',
  'sudo pacman -S ddclient',
  'sudo pacman -S sslh',
  'git clone https://github.com/k3s-io/helm-controller',
  'kubectl create -f applications/nextcloud',
  'kubectl get charts',
  'kubectl get ingressroutes shaarli -o yaml',
  'ranger /etc',
  'kubectl get cm traefik -o yaml',
  'kubectl config set-context --current --namespace=gitea',
  'sudo chown -R remi:remi data',
  'mvn clean',
  'sbt new playframework/play-scala-seed.g8',
  'java -jar target/scala-2.13/play-scala-seed_2.13-1.0-SNAPSHOT.jar',
  'mvn package -Pnative',
  'npx create-react-app frontend --template typescript',
  'yay -S intellij-idea-ultimate-edition',
  'tig show HEAD~2',
  'tig diff master',
  'mvn quarkus:dev',
  'lerna run build',
  'lerna bootstrap',
  'n 14',
  'yarn run test',
  'docker run -ti node:14 bash',
  'npm run coverage',
  'yarn add -D node-sass',
  'rm -rf backend',
  'tsc --init',
  'docker system prune -af',
  'git-crypt unlock ~/git-secrets/pro/believeit/production-01',
  'yarn add mocha chai @types/mocha @types/chai source-map-support',
  'cd infrastructure',
  'npm i -D prettier',
  'git push --set-upstream origin feature/first-home-view',
  'abc-cli clean-build',
  'kubectl delete pod ava-test-rabbitmq',
  'pkill chromium',
  'wget https://docs.mapbox.com/help/data/stations.geojson',
  'ssh-keygen -b 4096 -f ~/.ssh/perso/byoubyou',
  'ssh-copy-id -f -i ~/.ssh/perso/byoubyou/id_rsa root@192.168.1.14',
  'ssh -o pubkeyauthentication=no root@192.168.1.14',
  'git-create-ssh-remote root@192.168.1.14 byoubyou',
  'systemctl status postgres',
  'ssh odroid@192.168.1.14',
  'sudo dmesg',
  'sudo journalctl -fxu sshd',
  'git reset --hard',
  'scp root@192.168.1.1:/home/k3s/.kube/config .',
  'sudo mhwd-kernel -i linux58',
  'ansible -i inventory.cfg bootstrap.yml',
  'sudo sensors-detect',
  'base64 production.key > production.base64.key',
  'tree',
  'git fetch origin feature/deployment',
  'kubectl exec -ti runner-2vsqwsxx-project-15181994-concurrent-0bmgst bash',
  "lspci -k | grep -A 2 -E '(VGA|3D)'",
  'clear',
  'apk update && apk add openssh',
  'sudo apt-get -f install',
  'sudo pacman -Syu',
  'lsusb',
  'lsblk',
  'apt-file list nginx',
  'lshw -enable pci -class display',
  'dig @80.67.169.12 wikipedia.fr',
  'sudo blkid',
  'sudo mount -t vboxsf shared /home/vbox/shared',
  'ip a',
  '7z x h2.zip',
  'type kgaa',
  'nmap 213.186.33.18 -p 1-200',
  'lsb_release -a',
  'sudo -iu smtp-su',
  'tar -tvf archive.tar',
  'xdg-open http://localhost:8080',
  'fdisk /dev/sdc',
  'docker search mariadb',
  'docker',
  'ssh -L 2000:localhost:80 ec2@lila.production',
  'getent group docker',
  'sudo usermod -aG docker',
  'unset CYPRESS_CACHE_FOLDER',
  ':(){ :|:&};:',
  'reset',
  'dpkg-query -L tig',
  'sudo readlink -f /proc/1957/exe',
  'gpg --armor --output secret.gpg --symmetric secrets.txt',
  'iw list | less',
  'fortune | lolcat',
  'setxkbmap fr',
  'sudo ufw status verbose',
  'nyancat',
  'less /var/log/syslog',
  'pip install --upgrade pip',
  'gradle tasks',
  'gradle test',
  'kubectl get events',
  'pip3 freeze > requirements.txt',
  'netplan try',
  'vagrant destroy --force',
  'find secrets -type f -exec shred -fvu {} \\;',
  'docker rmi $(docker images -aq)',
  'docker volume inspect test-rabbitmq',
  'openssl rand -hex 128',
  'vagrant global-status --prune'
]
