- hosts: vps
  vars:
    project_root: "{{ playbook_dir }}/.."
    project_build: "{{ project_root }}/dist"
    www_root: "/var/www/remi-pace.fr/"

  tasks:
    - name: "Build project"
      shell: './ci.sh'
      args:
        chdir: '{{ project_root }}'
      delegate_to: localhost

    - name: "Ensure destination directory exists"
      file:
        path: "{{ www_root }}"
        state: directory
        recurse: yes
        owner: 'www-data'

    - name: "Send project to remote"
      synchronize:
        src: "{{ project_build }}/"
        dest: "{{ www_root }}"
        delete: yes

    - name: "Set correct owner on files"
      file:
        path: "{{ www_root }}"
        state: directory
        recurse: yes
        owner: 'www-data'
